#!/bin/bash

INSTALL_DIR=$HOME/.local/library/

setup(){
    here=$(dirname $0)
    [ -e $INSTALL_DIR/data ] && cp -r $INSTALL_DIR/data $here
    [ -e $INSTALL_DIR ] && rm -r $INSTALL_DIR && rm $HOME/Desktop/Library.desktop
    mkdir -p $INSTALL_DIR
    cp -r $here/* $INSTALL_DIR
    cd $INSTALL_DIR
    K=$(echo $INSTALL_DIR | sed 's/\//\\\//g')
    sed "s/install/$K/g" library.desktop  > app.desktop
    chmod +x app.desktop

    ln -s $PWD/app.desktop $HOME/Desktop/Library.desktop
    cp -r assets data
    echo "App installed"
}

[[ "$1" == "-r" ]] && setup

[ -e $INSTALL_DIR ] || setup

cd $INSTALL_DIR
python3 src/main.py || echo "Please install openpyxl and pyqt5"