#!/bin/bash

INSTALL_DIR=$HOME/.local/library/

setup(){
    here=$(dirname $0)
    mkdir -p $INSTALL_DIR
    cp -r $here/* $INSTALL_DIR
    cd $INSTALL_DIR
    cat library.desktop | sed 's/%install%/'$INSTALL_DIR'/g'  > app.desktop
    mv app.desktop library.desktop
    [[ $(whoami) == "root" ]] && desktop-file-install library.desktop
    pip install pyqt5
    pip install openpyxl
    cp -r assets data
}

[ -e $INSTALL_DIR ] || setup

cd $INSTALL_DIR
python3 src/main.py